
/*
	//Author Ashbir Dhiman
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartparkingproroject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashbir Dhiman
 */
public class cancel_reservation extends javax.swing.JFrame {

    /**
     * Creates new form cancel_reservation
     */
    public cancel_reservation(String user_id) {
        initComponents();
        jLabel1.setText(user_id);
        
       
            
try {
                
                
                
                String r="";
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/smartpark","root","");

                String b = "Select car_number from cardetail where carowner_id='"+user_id+"'  ";
                Statement st=co.createStatement();
                ResultSet rs=st.executeQuery(b);

                while(rs.next())
                {
                   
                   
                    r=rs.getString("car_number");
                    jComboBox1.addItem(r);

                }
                
                

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);

            }
    }

    private cancel_reservation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 241, 52));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 37, -1, -1));

        jButton1.setFont(new java.awt.Font("Gungsuh", 0, 24)); // NOI18N
        jButton1.setText("Cancel Reservation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 286, 93));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Se project\\Projectimages\\cancelres.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String user_id=jComboBox1.getSelectedItem().toString();
       String floor="";
        try {
                String r="";
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/smartpark","root","");

                String b = "Select * from floor_1 where car_number='"+user_id+"'  ";
                Statement st=co.createStatement();
                ResultSet rs=st.executeQuery(b);

                if(rs.next()==true)
                {
                    while (rs.next())
                            {
                                 r=rs.getString("car_number");
                                 floor="floor_1";
                            }
                }
                
                
                
                

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);

            }
        try {
                String r="";
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/smartpark","root","");

                String b = "Select * from floor_2 where car_number='"+user_id+"'  ";
                Statement st=co.createStatement();
                ResultSet rs=st.executeQuery(b);

                if(rs.next()==true)
                {
                    while (rs.next())
                            {
                                 r=rs.getString("car_number");
                                 floor="floor_2";
                            }
                } 

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);   }
        try {
                String r="";
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/smartpark","root","");

                String b = "Select * from floor_3 where car_number='"+user_id+"'  ";
                Statement st=co.createStatement();
                ResultSet rs=st.executeQuery(b);

                if(rs.next()==true)
                {
                    while (rs.next())
                            {
                                 r=rs.getString("car_number");
                                 floor="floor_3";
                            }
                }
             

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);

            }
        
        
        try {
                String r="";
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/smartpark","root","");

                String b = "delete from "+floor+" where car_number='"+user_id+"' ";
                Statement st=co.createStatement();
                st.execute(b);

                JOptionPane.showMessageDialog(this, "Cancelled  Sucessful");
                

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);

            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancel_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancel_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancel_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancel_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancel_reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
